name: Dispatch build of the freenas-proxmox plugin package

on:
  push:

jobs:
  dispatch:
    name: Dispatch to the build and packager workflow.
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch request to 'freenas-proxmox-packer' repo.
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: TheGrandWazoo/freenas-proxmox-packer
          event-type: build_push
          client-payload: '{"ref" : "${{ github.ref }}", "sha": "${{ github.sha }}"}'
