name: Mirroring

on: [push, delete]

jobs:
  to_azure:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://azure.da.lan:22/Datagile/Devops/_git/freenas-proxmox
          ssh_private_key:
            ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
